FROM composer/composer:php5

COPY ./php.ini /usr/local/etc/php/

#VOLUME
#COPY composer.json composer.lock ./

WORKDIR /var/www/budget
#RUN composer install --prefer-dist --no-interaction

ENTRYPOINT /bin/bash
CMD ["true"]
